# Generated by Django 4.2 on 2023-12-16 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_zone', models.CharField(default='Europe/Paris', max_length=50)),
                ('weather_api_key', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CateogryBlog',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='General', max_length=30, verbose_name='The category')),
                ('description', models.CharField(max_length=60, verbose_name='Description')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to=settings.AUTH_USER_MODEL, verbose_name='The category')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='The Title')),
                ('body', models.TextField(max_length=300, verbose_name='The Blog Post Content')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog', to=settings.AUTH_USER_MODEL, verbose_name='The author of the blog post')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weather_backend.cateogryblog', verbose_name='The category')),
            ],
        ),
    ]
